// <auto-generated />
using BlazorHotelBooking.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorHotelBooking.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231222164659_seeding")]
    partial class seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorHotelBooking.Shared.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DBPrice")
                        .HasColumnType("decimal(18,2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FamPrice")
                        .HasColumnType("decimal(18,2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SBPrice")
                        .HasColumnType("decimal(18,2");

                    b.Property<int>("Spaces")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DBPrice = 775m,
                            Description = "Experience luxury in the heart of the city, with sophisticated rooms and a stone's throw from London's major attractions and shopping districts.",
                            FamPrice = 950m,
                            Name = "Hilton London Hotel",
                            SBPrice = 375m,
                            Spaces = 20
                        },
                        new
                        {
                            Id = 2,
                            DBPrice = 500m,
                            Description = "Indulge in elegance and comfort at this centrally located hotel, featuring top-notch amenities and easy access to London's historical landmarks",
                            FamPrice = 900m,
                            Name = "London Marriott Hotel",
                            SBPrice = 300m,
                            Spaces = 20
                        },
                        new
                        {
                            Id = 3,
                            DBPrice = 120m,
                            Description = " Enjoy affordable comfort with stunning seafront views, ideally situated for exploring Brighton’s vibrant beach and pier attractions.",
                            FamPrice = 150m,
                            Name = "Travelodge Brighton Seafront",
                            SBPrice = 80m,
                            Spaces = 20
                        },
                        new
                        {
                            Id = 4,
                            DBPrice = 400m,
                            Description = "A charming, budget-friendly hotel on Brighton’s seafront, offering cozy accommodations with easy access to the city's lively nightlife and cultural sites",
                            FamPrice = 520m,
                            Name = "Kings Hotel Brighton",
                            SBPrice = 180m,
                            Spaces = 20
                        },
                        new
                        {
                            Id = 5,
                            DBPrice = 400m,
                            Description = "Modern and stylish, this hotel provides a comfortable base to discover Brighton, conveniently close to the beach and the buzzing city center.",
                            FamPrice = 520m,
                            Name = "Leonardo Hotel Brighton",
                            SBPrice = 180m,
                            Spaces = 20
                        },
                        new
                        {
                            Id = 6,
                            DBPrice = 100m,
                            Description = "Nestled in the Scottish Highlands, this inn offers a serene getaway with scenic views, perfect for outdoor enthusiasts and nature lovers",
                            FamPrice = 155m,
                            Name = "Nevis Bank Inn, Fort William",
                            SBPrice = 90m,
                            Spaces = 20
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
